<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShop\PrestaShop\Core\Module\ModuleOverrideChecker' shared service.

return $this->services['PrestaShop\\PrestaShop\\Core\\Module\\ModuleOverrideChecker'] = new \PrestaShop\PrestaShop\Core\Module\ModuleOverrideChecker(($this->services['translator'] ?? $this->getTranslatorService()), (\dirname(__DIR__, 4).'/override/'));
