<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'product_comment_criterion_form_data_handler' shared service.

return $this->services['product_comment_criterion_form_data_handler'] = new \PrestaShop\Module\ProductComment\Form\ProductCommentCriterionFormDataHandler(($this->services['product_comment_criterion_repository'] ?? $this->load('getProductCommentCriterionRepositoryService.php')), ($this->services['prestashop.core.admin.lang.repository'] ?? $this->getPrestashop_Core_Admin_Lang_RepositoryService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));
