<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'product_comment_criterion_form_data_provider' shared service.

return $this->services['product_comment_criterion_form_data_provider'] = new \PrestaShop\Module\ProductComment\Form\ProductCommentCriterionFormDataProvider(($this->services['product_comment_criterion_repository'] ?? $this->load('getProductCommentCriterionRepositoryService.php')), ($this->services['prestashop.core.admin.lang.repository'] ?? $this->getPrestashop_Core_Admin_Lang_RepositoryService()));
