<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'PrestaShopBundle\Controller\Admin\SecuredFileReaderController' shared service.

return $this->services['PrestaShopBundle\\Controller\\Admin\\SecuredFileReaderController'] = new \PrestaShopBundle\Controller\Admin\SecuredFileReaderController((\dirname(__DIR__, 4).'/upload/'));
