<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBl9BhxG\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBl9BhxG/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBl9BhxG.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBl9BhxG\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBl9BhxG\appAppKernelProdContainer([
    'container.build_hash' => 'Bl9BhxG',
    'container.build_id' => 'fdf2cc8e',
    'container.build_time' => 1758374990,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBl9BhxG');
