services:
  psxmarketingwithgoogle.billing_env:
    class: 'PrestaShop\Module\PsxMarketingWithGoogle\Factory\ParametersFactory'
    public: true
    factory: ['PrestaShop\Module\PsxMarketingWithGoogle\Factory\ParametersFactory', 'getBillingEnv']
