parameters:
  psshipping.sentry_dsn: "https://78c41abf489931010a3a83cacc14926b@o298402.ingest.sentry.io/4505906299600896"
  psshipping.sentry_env: "production"

  # Either or not using a billing stub
  psshipping.ps_billing_sandbox: 0

  # To enable hot reload for vue app, it only works in dev mode (pnpm dev)
  # if set to false it will use a build watch mode
  psshipping.vue_app_dev_mode: 0

  # URL on which to get the vue app
  psshipping.cdn_url: 'https://assets.prestashop3.com/shipping'

  # URL to communicate with psshipping APIs
  psshipping.api_url: 'https://shipping-api.prestashop.com'

  # URL to load CDC cloudsync
  psshipping.cloudsync_cdc_url: 'https://assets.prestashop3.com/ext/cloudsync-merchant-sync-consent/latest/cloudsync-cdc.js'

  # set to 1 => it will use the local vue app
  # set to 0 => use the CDN, in this case do not forget to specify psshipping.cdn_url variable
  psshipping.use_local_vue_app: 0

  psshipping.mbe_tracking_url: "https://www.mbe.it/en/tracking?c=@"

  psshipping.segment_key: "3XsHeI2dfKoKE2wReGp7IO2bLa5hbeVB"
